"""init tables

Revision ID: 0001_init
Revises: 
Create Date: 2025-08-13 16:17:46.500997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_init'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_budget_code'), 'budget', ['budget_code'], unique=True)
    op.create_table('material_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('system_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_equipment_id'), 'material_equipment', ['id'], unique=False)
    op.create_index(op.f('ix_material_equipment_name'), 'material_equipment', ['name'], unique=False)
    op.create_table('technical_spec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_spec_spec_code'), 'technical_spec', ['spec_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technical_spec_spec_code'), table_name='technical_spec')
    op.drop_table('technical_spec')
    op.drop_index(op.f('ix_material_equipment_name'), table_name='material_equipment')
    op.drop_index(op.f('ix_material_equipment_id'), table_name='material_equipment')
    op.drop_table('material_equipment')
    op.drop_index(op.f('ix_budget_budget_code'), table_name='budget')
    op.drop_table('budget')
    # ### end Alembic commands ###
