
# Generated by Alembic (custom template)
# Project: auto-qm-form
# NOTE: 請勿手動調整 revision / down_revision；請使用 Alembic 指令。
# SPDX-License-Identifier: MIT
# TEMPLATE_VERSION: 2.2

"""author email check

Revision ID: 3bc2b7b22be1
Revises: 5d6f8ef7ace6
Create Date (UTC): 2025-08-22 22:34:44
Git Commit (generation time): 3a029ef7bbfa
Git Branch (generation time): master
Author: Pancharry <cahrry.lin@hotmail.com>
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision: str = '3bc2b7b22be1'
down_revision: str | None = '5d6f8ef7ace6'
branch_labels: tuple[str, ...] | str | None = None
depends_on: tuple[str, ...] | str | None = None
git_commit: str = '3a029ef7bbfa'
git_branch: str = 'master'
author_name: str = 'Pancharry'
author_email: str = 'cahrry.lin@hotmail.com'
TEMPLATE_VERSION = '2.2'
MIGRATION_META: dict[str, str | None] = {
    'revision': '3bc2b7b22be1',
    'down_revision': "'5d6f8ef7ace6'",
    'create_utc': '2025-08-22 22:34:44',
    'git_commit': '3a029ef7bbfa',
    'git_branch': 'master',
    'author_name': 'Pancharry',
    'author_email': 'cahrry.lin@hotmail.com',
    'template_version': '2.2',
    'message': 'author email check',
}

def upgrade() -> None:
    pass

def downgrade() -> None:
    pass