
# Generated by Alembic (custom template)
# Project: auto-qm-form
# NOTE: 請勿手動調序號，透過 Alembic 指令產生。
# SPDX-License-Identifier: MIT

"""add something

Revision ID: e48cb4a4d81e
Revises: 
Create Date: 2025-08-20 23:02:05 (UTC)

這個檔案是由 Alembic 產生。
- 修改 upgrade()/downgrade() 內容以變更 schema。
- 避免手動調整 revision / down_revision 以免破壞拓撲。
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
# 若需要引用 enum / JSON / 其他型別，可於此新增 import
# import sqlalchemy.dialects.postgresql as psql

# ------------------------------------------------------------
# Revision identifiers
# ------------------------------------------------------------
revision: str = 'e48cb4a4d81e'
down_revision: str | None = None
branch_labels: tuple[str, ...] | str | None = None
depends_on: tuple[str, ...] | str | None = None

# ------------------------------------------------------------
# UPGRADE: 由舊版 -> 這個新版
# ------------------------------------------------------------
def upgrade() -> None:
    """
    實作 schema 升級。
    建議：
      - 對於新增欄位若需 default，先 nullable=True 再填值再改為 nullable=False
      - 大表加索引前可考慮 concurrently（PostgreSQL） -> 另寫手動 SQL
    """
    # === 自動產生區塊開始（Alembic autogenerate 可能插入 op.create_table 等） ===
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    # === 自動產生區塊結束 ===

# ------------------------------------------------------------
# DOWNGRADE: 從這個新版 -> 回到父版本
# ------------------------------------------------------------
def downgrade() -> None:
    """
    還原 upgrade() 所做的變更。
    注意：
      - 破壞性操作（drop table / column）要謹慎
      - 若無法安全還原，可在此 raise RuntimeError 提示
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###