
# Generated by Alembic (custom template)
# Project: auto-qm-form
# NOTE: 請勿手動調整 revision / down_revision；請使用 Alembic 指令。
# SPDX-License-Identifier: MIT
# TEMPLATE_VERSION: 2.1

"""merge branches

Revision ID: 5dd2ce6abf54
Revises: 
Create Date: 2025-08-22 21:33:24 (UTC)
Git Commit (generation time): 3a029ef7bbfa
Git Branch (generation time): master
Author: Pancharry <cahrry.lin@hotmail.com>

說明：
  - 本檔案由自訂 Alembic 模板 (TEMPLATE_VERSION 2.1) 產生。
  - Git commit / branch / 作者資訊 取得優先序：
      環境變數 (GIT_COMMIT / GIT_BRANCH / GIT_AUTHOR_*) > git 指令 > fallback。
  - 若 git_commit 為 'unknown'：代表非 git 環境或無法取得。
  - MIGRATION_META 可供後續統計或內部工具解析。
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# ------------------------------------------------------------
# Revision identifiers & Metadata
# ------------------------------------------------------------
revision: str = '5dd2ce6abf54'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None
git_commit: str = '3a029ef7bbfa'
git_branch: str = 'master'
author_name: str = 'Pancharry'
author_email: str = 'cahrry.lin@hotmail.com'
TEMPLATE_VERSION = "2.1"
MIGRATION_META: dict[str, str | None] = {
    'revision': '5dd2ce6abf54',
    'down_revision': None,
    'create_utc': '2025-08-22 21:33:24',
    'git_commit': '3a029ef7bbfa',
    'git_branch': 'master',
    'author_name': 'Pancharry',
    'author_email': 'cahrry.lin@hotmail.com',
    'template_version': '2.1',
    'message': 'merge branches',
}

# ------------------------------------------------------------
# UPGRADE
# ------------------------------------------------------------
def upgrade() -> None:
    """
    Apply schema changes.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


# ------------------------------------------------------------
# DOWNGRADE
# ------------------------------------------------------------
def downgrade() -> None:
    """
    Revert schema changes.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

# ------------------------------------------------------------
# 備註：
# 1. git_* / author_* 為產生時快照。
# 2. 需要 autogenerate 實際操作時，請將 pass 替換為 Alembic 自動輸出或手動指令。
# ------------------------------------------------------------