"""initial

Revision ID: 88179a39b080
Revises: 
Create Date: 2025-08-20 22:51:52.709861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88179a39b080'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blank_templates',
    sa.Column('template_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_name', sa.String(length=128), nullable=False),
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('template_id', name=op.f('pk_blank_templates'))
    )
    op.create_index(op.f('ix_blank_templates_file_id'), 'blank_templates', ['file_id'], unique=False)
    op.create_index(op.f('ix_blank_templates_template_name'), 'blank_templates', ['template_name'], unique=True)
    op.create_table('budget_items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budget_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_budget_items'))
    )
    op.create_index(op.f('ix_budget_items_budget_id'), 'budget_items', ['budget_id'], unique=False)
    op.create_index(op.f('ix_budget_items_name'), 'budget_items', ['name'], unique=False)
    op.create_index('ix_budget_items_name_type', 'budget_items', ['name', 'type'], unique=False)
    op.create_table('quality_standards',
    sa.Column('standard_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('inspection_items', sa.JSON(), nullable=True),
    sa.Column('inspection_methods', sa.JSON(), nullable=True),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=True),
    sa.Column('frequency', sa.String(length=128), nullable=True),
    sa.Column('responsible_party', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('standard_id', name=op.f('pk_quality_standards'))
    )
    op.create_index('ix_quality_standards_item', 'quality_standards', ['item_name', 'item_type'], unique=False)
    op.create_index(op.f('ix_quality_standards_item_name'), 'quality_standards', ['item_name'], unique=False)
    op.create_index(op.f('ix_quality_standards_item_type'), 'quality_standards', ['item_type'], unique=False)
    op.create_table('reference_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('project_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_files'))
    )
    op.create_index(op.f('ix_reference_files_file_id'), 'reference_files', ['file_id'], unique=False)
    op.create_table('spec_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spec_id', sa.String(length=64), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.String(length=32), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('standards', sa.JSON(), nullable=True),
    sa.Column('testing_methods', sa.JSON(), nullable=True),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spec_items'))
    )
    op.create_index(op.f('ix_spec_items_item_name'), 'spec_items', ['item_name'], unique=False)
    op.create_index(op.f('ix_spec_items_spec_id'), 'spec_items', ['spec_id'], unique=False)
    op.create_table('stored_files',
    sa.Column('file_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('file_id', name=op.f('pk_stored_files'))
    )
    op.create_table('temp_standard_files',
    sa.Column('temp_file_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budget_id', sa.String(length=64), nullable=False),
    sa.Column('spec_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('temp_file_id', name=op.f('pk_temp_standard_files'))
    )
    op.create_index(op.f('ix_temp_standard_files_budget_id'), 'temp_standard_files', ['budget_id'], unique=False)
    op.create_index(op.f('ix_temp_standard_files_spec_id'), 'temp_standard_files', ['spec_id'], unique=False)
    op.create_table('generated_forms',
    sa.Column('form_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temp_file_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('form_name', sa.String(length=255), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('file_format', sa.String(length=16), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['temp_file_id'], ['temp_standard_files.temp_file_id'], name=op.f('fk_generated_forms_temp_file_id_temp_standard_files')),
    sa.ForeignKeyConstraint(['template_id'], ['blank_templates.template_id'], name=op.f('fk_generated_forms_template_id_blank_templates')),
    sa.PrimaryKeyConstraint('form_id', name=op.f('pk_generated_forms'))
    )
    op.create_index(op.f('ix_generated_forms_file_id'), 'generated_forms', ['file_id'], unique=False)
    op.create_index(op.f('ix_generated_forms_form_name'), 'generated_forms', ['form_name'], unique=False)
    op.create_table('temp_standard_items',
    sa.Column('temp_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temp_file_id', sa.Integer(), nullable=False),
    sa.Column('budget_item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('reference_standard_id', sa.Integer(), nullable=True),
    sa.Column('inspection_items', sa.JSON(), nullable=True),
    sa.Column('inspection_methods', sa.JSON(), nullable=True),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=True),
    sa.Column('frequency', sa.String(length=128), nullable=True),
    sa.Column('responsible_party', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_modified', sa.Boolean(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['budget_item_id'], ['budget_items.item_id'], name=op.f('fk_temp_standard_items_budget_item_id_budget_items')),
    sa.ForeignKeyConstraint(['reference_standard_id'], ['quality_standards.standard_id'], name=op.f('fk_temp_standard_items_reference_standard_id_quality_standards')),
    sa.ForeignKeyConstraint(['temp_file_id'], ['temp_standard_files.temp_file_id'], name=op.f('fk_temp_standard_items_temp_file_id_temp_standard_files')),
    sa.PrimaryKeyConstraint('temp_item_id', name=op.f('pk_temp_standard_items'))
    )
    op.create_index(op.f('ix_temp_standard_items_item_name'), 'temp_standard_items', ['item_name'], unique=False)
    op.create_index(op.f('ix_temp_standard_items_item_type'), 'temp_standard_items', ['item_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_standard_items_item_type'), table_name='temp_standard_items')
    op.drop_index(op.f('ix_temp_standard_items_item_name'), table_name='temp_standard_items')
    op.drop_table('temp_standard_items')
    op.drop_index(op.f('ix_generated_forms_form_name'), table_name='generated_forms')
    op.drop_index(op.f('ix_generated_forms_file_id'), table_name='generated_forms')
    op.drop_table('generated_forms')
    op.drop_index(op.f('ix_temp_standard_files_spec_id'), table_name='temp_standard_files')
    op.drop_index(op.f('ix_temp_standard_files_budget_id'), table_name='temp_standard_files')
    op.drop_table('temp_standard_files')
    op.drop_table('stored_files')
    op.drop_index(op.f('ix_spec_items_spec_id'), table_name='spec_items')
    op.drop_index(op.f('ix_spec_items_item_name'), table_name='spec_items')
    op.drop_table('spec_items')
    op.drop_index(op.f('ix_reference_files_file_id'), table_name='reference_files')
    op.drop_table('reference_files')
    op.drop_index(op.f('ix_quality_standards_item_type'), table_name='quality_standards')
    op.drop_index(op.f('ix_quality_standards_item_name'), table_name='quality_standards')
    op.drop_index('ix_quality_standards_item', table_name='quality_standards')
    op.drop_table('quality_standards')
    op.drop_index('ix_budget_items_name_type', table_name='budget_items')
    op.drop_index(op.f('ix_budget_items_name'), table_name='budget_items')
    op.drop_index(op.f('ix_budget_items_budget_id'), table_name='budget_items')
    op.drop_table('budget_items')
    op.drop_index(op.f('ix_blank_templates_template_name'), table_name='blank_templates')
    op.drop_index(op.f('ix_blank_templates_file_id'), table_name='blank_templates')
    op.drop_table('blank_templates')
    # ### end Alembic commands ###
